from pathlib import Path

BASE_DIRECTORY: Path = Path(__file__).resolve().parent.parent

DATA_DIRECTORY = BASE_DIRECTORY / "data"
DATA_TRAIN_DIRECTORY = DATA_DIRECTORY / "train"
CAT_DATA_TRAIN_DIRECTORY = DATA_TRAIN_DIRECTORY / "cat"
DATA_TEST_DIRECTORY = DATA_DIRECTORY / "test"
CAT_DATA_TEST_DIRECTORY = DATA_TEST_DIRECTORY / "cat"